name: main

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Just
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify Just
        run: |
          just --version

      - name: Install or build Python 2.7
        run: |
          just install-python2

      - name: Install Python 2.7 package dependencies
        run: |
          just install-python2-deps

      - name: Create Python 2.7 virtual environment
        run: |
          just create-venv

      - name: Install package with dependencies
        run: |
          just install

      - name: Build package
        run: |
          just build

      - name: List package artifacts
        run: |
          ls -la autobahntestsuite/dist/

      - name: Test installation
        run: |
          just test-version
          just test-wstest

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: autobahntestsuite/dist/

  docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Build documentation
        run: just docs

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/html/

      - name: Deploy to Read the Docs
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "Documentation built. RTD will auto-deploy on tag push."
          echo "Make sure RTD webhook is configured for this repository."
